server:
  port: ${PORT:8080}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: pagoya
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        model: gpt-4o-mini
      embedding:
        model: text-embedding-3-small
    vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: 1536
